import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./output.css";
// import "./dark.js";
import Image from "next/image";
import DarkBtn from "../../components/DarkBtn/Dark";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <>
      <html lang="fa" dir="rtl">
        <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>وبسایت شخصی من</title>
          <link rel="stylesheet" href="./output.css" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-white-900`}>
          <div className="group float-settings">
            <div className="w-10 flex flex-col items-center justify-center h-full p-2 group-hover:-translate-x-[20px] transition-all duration-300">
              <button id="theme-light" type="button" className="py-1 px-3 mb-2 rounded">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" className="bi bi-brightness-high-fill" viewBox="0 0 16 16">
                  <path
                    d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0m0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13m8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5M3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8m10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0m-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0m9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707M4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708"
                  />
                </svg>
              </button>
              <button id="theme-dark" type="button" className="py-1 px-3 mb-2 rounded">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" className="bi bi-moon-fill" viewBox="0 0 16 16">
                  <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278" />
                </svg>
              </button>
              <button id="back-history" type="button" className="py-1 px-3 mb-2 rounded">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" className="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                  <path fillRule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z" />
                </svg>
              </button>
              <button id="forward-history" type="button" className="py-1 px-3 mb-2 rounded">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" className="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                  <path fillRule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5z" />
                </svg>
              </button>
            </div>
          </div>
          <div className="2xl:mx-[250px] xl:mx-[200px] lg:mx-[130px] mx-[50px] -z-10">
            <nav id="nav-items" className="h-12 w-full mt-5 border-y-2 border-y-fuchsia-950 py-2">
              <ul className="grid grid-cols-4 md:gap-x-15 nav-ul-responsive w-full h-full">
                <li className="nav-li shadow-lg w-1/2">
                  <Link href={"/"} className="block">صفحه اصلی</Link>
                </li>
                <li className="nav-li shadow-lg w-1/2">
                  <Link href={"/blog"} className="block">نوشته ها</Link>
                </li>
                <li className="nav-li shadow-lg w-1/2">
                  <a className="block" href="">روزمه من</a>
                </li>
                <li className="nav-li shadow-lg w-1/2">
                  <a className="block" href="">انیمه های من</a>
                </li>
              </ul>
            </nav>

            <main className="my-8">
              <section id="about-me" className="mb-8 md:grid md:grid-cols-6 gap-4 border-2 rounded-md">
                <div className="md:col-span-2 flex justify-center items-center">
                  <Image src={"/img/img2.jpg"} alt="About-Me" width={300} height={300} className="h-auto 2xs:mt-2 md:h-[55%] lg:h-[70%] rounded-lg shadow-lg w-[95%] xs:mt-2 lg:mt-0 md:mt-0"></Image>
                </div>
                <div className="md:col-span-4 p-4 flex flex-col 2xs:p-0 2xs:text-[8px] sm:text-[16px] xs:text-[14px]">
                  <h1 className="dark:text-white font-bold mx-3 my-4 p-4 md:text-3xl">درباره من</h1>
                  <p className="dark:text-white mx-3 p-5 text-justify md:text-lg self-start">
                    من حمیدرضا رضایی هستم فارغ التحصیل رشته مهندسی کامپیوتر از کلاس اول دبستان عاشق کامپیوتر بودم هستم و خواهم بود اما بنا به دلیل هایی رفتم رشته تجربی خوندم و از آناتومی بدن اطلاعات زیادی پیدا کردم اما عشقم به کامپیوتر کم نشد و در دانشگاه رشته کامپیوتر رو انتخاب کردم و الان
                    مهندس کامپیوتر شد بلافاصله زبان برنامه نویسی پایتون رو یاد گرفتم و رفتم سراغ وب چون کد نویسی رو خیلی دوست داشتم فقط کد نویسی بک اند رو یاد گرفتم با فرم ورک جنگو.
                  </p>
                </div>
              </section>

              {children}

            </main>
            <footer className="bg-white dark:bg-[rgb(37,0,36)] dark:text-gray-50 xs:text-[18px] shadow-md py-4 mt-8 2xs:text-[10px] text-center">
              <p>
                تمامی حقوق مادی و معنوی این وبسایت متعلق به
                <span className="font-bold">حمیدرضا رضایی</span>
                می باشد
              </p>
            </footer>
          </div>
          <script><DarkBtn /></script>
        </body>
      </html>
    </>
  );
}
